from .section_open_directory import OpenDirectorySection
from .section_statistical_values import StatisticalValueSection
from .section_boxplot import BoxplotSection
from .section_statistical_test import StatisticalTestSection